CREATE PROCEDURE INSERT_PROCESSO_DESPACHO
      @tableProcessoDespachos PROCESSODESPACHOTYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.PROCESSO_DESPACHO
	        ( ID_PROCESSO ,
	          ID_DESPACHO ,
	          NUMERO_RPI ,
	          DATA_DESPACHO ,
	          ID_PROTOCOLO ,
	          COMPLEMENTO
	        )
	SELECT
		PRO.ID,
		DESP.ID,
		NEW.NUMERO_RPI,
		NEW.DATA_DESPACHO,
		PRT.ID,
		NEW.COMPLEMENTO
	FROM
		@tableProcessoDespachos		NEW
		JOIN PROCESSO				PRO WITH (NOLOCK) ON PRO.NUMERO = NEW.NUMERO_PROCESSO
		JOIN DESPACHO				DESP WITH (NOLOCK) ON DESP.CODIGO = NEW.CODIGO_DESPACHO
		LEFT JOIN PROTOCOLO			PRT WITH (NOLOCK) ON PRT.NUMERO = NEW.NUMERO_PROTOCOLO

END
go

