CREATE PROCEDURE UPDATE_PROCESSO_CLASSE
      @tableClasses PROCESSOCLASSETYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM dbo.PROCESSO_CLASSE
	FROM
		PROCESSO_CLASSE		OLD
		JOIN PROCESSO		PRO ON PRO.ID = OLD.ID_PROCESSO
		JOIN @tableClasses	NEW ON NEW.NUMERO_PROCESSO = PRO.NUMERO

	INSERT dbo.PROCESSO_CLASSE
	SELECT
	  PRO.ID,
	  NEW.NUMERO_CLASSE,
	  TSC.TIPO,
	  NEW.ESPECIFICACAO
	FROM
	  @tableClasses			            NEW
	  JOIN dbo.PROCESSO		            PRO ON PRO.NUMERO = NEW.NUMERO_PROCESSO
	  JOIN dbo.TIPO_SITUACAO_CLASSE     TSC ON TSC.DESCRICAO = NEW.TIPO_DESCRICAO

END
go
