CREATE PROCEDURE [dbo].[UPDATE_PROCESSO_TITULAR]
      @tableTitulares PROCESSOTITULARTYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM PROCESSO_CLASSE
	FROM
		PROCESSO_CLASSE		OLD
		JOIN PROCESSO		PRO ON PRO.ID = OLD.ID_PROCESSO
		JOIN @tableTitulares	NEW ON NEW.NUMERO_PROCESSO = PRO.NUMERO

	INSERT PROCESSO_CLASSE
	--(ID_PROCESSO, NUMERO_CLASSE, TIPO, ESPECIFICAO, TRADUCAO_ESPECIFICACAO, NUMERO_RPI)
	SELECT
	  PRO.ID,
	  NEW.NUMERO_CLASSE,
	  TSC.TIPO,
	  NEW.ESPECIFICACAO,
	  NEW.TRADUCAO_ESPECIFICACAO,
	  NEW.NUMERO_RPI
	FROM
	  @tableTitulares			            NEW
	  JOIN dbo.PROCESSO		            PRO ON PRO.NUMERO = NEW.NUMERO_PROCESSO
	  JOIN dbo.TIPO_SITUACAO_CLASSE     TSC ON TSC.DESCRICAO = NEW.TIPO_DESCRICAO

END