CREATE PROCEDURE [dbo].[UPDATE_PROCESSO]
		@tableProcessos PROCESSOTYPE READONLY
AS
BEGIN
	SET NOCOUNT ON;

	MERGE INTO dbo.PROCESSO PRO
	USING @tableProcessos NEWPRO ON NEWPRO.NUMERO = PRO.NUMERO
	WHEN MATCHED THEN
		UPDATE SET
			PRO.NOME_TITULAR = SUBSTRING(COALESCE(NEWPRO.NOME_TITULAR, PRO.NOME_TITULAR), 1, 500),
			PRO.CPF_CNPJ_INPI_TITULAR = SUBSTRING(COALESCE(NEWPRO.CPF_CNPJ_INPI_TITULAR, PRO.CPF_CNPJ_INPI_TITULAR), 1, 100),
			PRO.PAIS_TITULAR = SUBSTRING(COALESCE(NEWPRO.PAIS_TITULAR, PRO.PAIS_TITULAR), 1, 50),
			PRO.UF_TITULAR = SUBSTRING(COALESCE(NEWPRO.UF_TITULAR, PRO.UF_TITULAR), 1, 2),
			PRO.NOME_PROCURADOR = SUBSTRING(COALESCE(NEWPRO.NOME_PROCURADOR, PRO.NOME_PROCURADOR), 1, 1000),
			PRO.MARCA = SUBSTRING(COALESCE(NEWPRO.MARCA, PRO.MARCA), 1, 1000),
			PRO.MARCA_ORTOGRAFADA = SUBSTRING(COALESCE(NEWPRO.MARCA_ORTOGRAFADA, PRO.MARCA_ORTOGRAFADA), 1, 1000),
			PRO.MARCA_NAO_ORTOGRAFADA = SUBSTRING(COALESCE(NEWPRO.MARCA_NAO_ORTOGRAFADA, PRO.MARCA_NAO_ORTOGRAFADA), 1, 1000),
			PRO.MARCA_SEM_VOGAIS = SUBSTRING(COALESCE(NEWPRO.MARCA_SEM_VOGAIS, PRO.MARCA_SEM_VOGAIS), 1, 100),
			PRO.PRIORIDADE = SUBSTRING(COALESCE(NEWPRO.PRIORIDADE, PRO.PRIORIDADE), 1, 100),
			PRO.DATA_PRIORIDADE = COALESCE(NEWPRO.DATA_PRIORIDADE, PRO.DATA_PRIORIDADE),
			PRO.NOME_PAIS_PRIORIDADE = SUBSTRING(COALESCE(NEWPRO.NOME_PAIS_PRIORIDADE, PRO.NOME_PAIS_PRIORIDADE), 1, 2),
			PRO.TIPO_APRESENTACAO = COALESCE(NEWPRO.TIPO_APRESENTACAO, PRO.TIPO_APRESENTACAO),
			PRO.TIPO_NATUREZA = COALESCE(dbo.GetNatureByDescription(NEWPRO.TIPO_NATUREZA_DESCRICAO), PRO.TIPO_NATUREZA),
			PRO.CLASSE_INTERNACIONAL = SUBSTRING(COALESCE(NEWPRO.CLASSE_INTERNACIONAL, PRO.CLASSE_INTERNACIONAL), 1 , 5),
			PRO.CLASSE_1 = SUBSTRING(COALESCE(NEWPRO.CLASSE_1, PRO.CLASSE_1), 1, 5),
			PRO.CLASSE_2 = SUBSTRING(COALESCE(NEWPRO.CLASSE_2, PRO.CLASSE_2), 1, 5),
			PRO.CLASSE_3 = SUBSTRING(COALESCE(NEWPRO.CLASSE_3, PRO.CLASSE_3), 1, 5),
			PRO.ESPECIFICACAO = COALESCE(NEWPRO.ESPECIFICACAO, PRO.ESPECIFICACAO),
			PRO.APOSTILA = COALESCE(NEWPRO.APOSTILA, PRO.APOSTILA),
			PRO.NUMERO_REFERENCIA = COALESCE(NEWPRO.NUMERO_REFERENCIA, PRO.NUMERO_REFERENCIA),
			PRO.DATA_DEPOSITO = COALESCE(NEWPRO.DATA_DEPOSITO, PRO.DATA_DEPOSITO),
			PRO.DATA_CONCESSAO = COALESCE(NEWPRO.DATA_CONCESSAO, PRO.DATA_CONCESSAO),
			PRO.DATA_REGISTRO = COALESCE(NEWPRO.DATA_REGISTRO, PRO.DATA_REGISTRO),
			PRO.DATA_VIGENCIA = COALESCE(NEWPRO.DATA_VIGENCIA, PRO.DATA_VIGENCIA),
			PRO.DATA_ORDINARIO_INICIAL = COALESCE(DATEADD(DAY, 1, DATEADD(YEAR, 10, DATEADD(YEAR, -1, NEWPRO.DATA_REGISTRO))), PRO.DATA_ORDINARIO_INICIAL),
			PRO.DATA_ORDINARIO_FINAL = COALESCE(DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO), PRO.DATA_ORDINARIO_FINAL),
			PRO.DATA_EXTRA_ORDINARIO_INICIAL = COALESCE(DATEADD(DAY, 1, DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO)), PRO.DATA_EXTRA_ORDINARIO_INICIAL),
			PRO.DATA_EXTRA_ORDINARIO_FINAL = COALESCE(DATEADD(MONTH, 6, DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO)), PRO.DATA_EXTRA_ORDINARIO_FINAL),
		    PRO.NUMERO_INSCRICAO_INTERNACIONAL = COALESCE(NEWPRO.NUMERO_INSCRICAO_INTERNACIONAL, PRO.NUMERO_INSCRICAO_INTERNACIONAL),
            PRO.DATA_RECEBIMENTO_INPI = COALESCE(NEWPRO.DATA_RECEBIMENTO_INPI, PRO.DATA_RECEBIMENTO_INPI)

	WHEN NOT MATCHED THEN
		INSERT
		VALUES
		(
			SUBSTRING(NEWPRO.NUMERO, 1, 20),
			SUBSTRING(NEWPRO.NOME_TITULAR, 1, 500),
			SUBSTRING(NEWPRO.CPF_CNPJ_INPI_TITULAR, 1, 100),
			SUBSTRING(NEWPRO.NOME_PROCURADOR, 1, 500),
			SUBSTRING(NEWPRO.MARCA, 1, 1000),
			SUBSTRING(NEWPRO.MARCA_ORTOGRAFADA, 1, 1000),
			SUBSTRING(NEWPRO.PRIORIDADE, 1, 100),
			NEWPRO.DATA_PRIORIDADE,
			SUBSTRING(NEWPRO.NOME_PAIS_PRIORIDADE, 1, 2),
			NEWPRO.TIPO_APRESENTACAO,
			dbo.GetNatureByDescription(NEWPRO.TIPO_NATUREZA_DESCRICAO),
			SUBSTRING(NEWPRO.CLASSE_INTERNACIONAL, 1, 5),
			SUBSTRING(NEWPRO.CLASSE_1, 1, 5),
			SUBSTRING(NEWPRO.CLASSE_2, 1, 5),
			SUBSTRING(NEWPRO.CLASSE_3, 1, 5),
			NEWPRO.ESPECIFICACAO,
			NEWPRO.APOSTILA,
			SUBSTRING(NEWPRO.NUMERO_REFERENCIA, 1, 255),
			NEWPRO.DATA_DEPOSITO,
			NEWPRO.DATA_CONCESSAO,
			NEWPRO.DATA_REGISTRO,
			NEWPRO.DATA_VIGENCIA,
			DATEADD(DAY, 1, DATEADD(YEAR, 10, DATEADD(YEAR, -1, NEWPRO.DATA_REGISTRO))),
			DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO),
			DATEADD(DAY, 1, DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO)),
			DATEADD(DAY, 181, DATEADD(YEAR, 10, NEWPRO.DATA_REGISTRO)),
			SUBSTRING(NEWPRO.PAIS_TITULAR, 1, 50),
			SUBSTRING(NEWPRO.UF_TITULAR, 1, 2),
			SUBSTRING(NEWPRO.MARCA_NAO_ORTOGRAFADA, 1, 1000),
			SUBSTRING(NEWPRO.MARCA_SEM_VOGAIS, 1, 1000),
		    NEWPRO.NUMERO_INSCRICAO_INTERNACIONAL,
		    NEWPRO.DATA_RECEBIMENTO_INPI
		);
END