IF NOT EXISTS(
				SELECT
					*
				FROM 
					SYS.systypes
				WHERE
					name = 'PROCESSODESPACHOTYPE'
			 )
BEGIN

	CREATE TYPE PROCESSODESPACHOTYPE AS TABLE
	(
		[NUMERO_PROCESSO] [varchar] (20) PRIMARY KEY NONCLUSTERED NOT NULL,
		[CODIGO_DESPACHO] [varchar] (100) NOT NULL,
		[NUMERO_RPI] [int] NOT NULL,
		[DATA_DESPACHO] [datetime2] NOT NULL,
		[NUMERO_PROTOCOLO] [varchar] (20) NULL,
		[COMPLEMENTO] [varchar] (MAX) NULL
	)
	WITH
    (MEMORY_OPTIMIZED = ON)
	

PRINT 'O Type "PROCESSODESPACHOTYPE" foi criado com sucesso'
END
ELSE
  PRINT 'O Type "PROCESSODESPACHOTYPE" já existe!'
GO