IF NOT EXISTS(
				SELECT
					*
				FROM 
					SYS.systypes
				WHERE
					name = 'PROCESSOTYPE'
			 )
BEGIN

	CREATE TYPE PROCESSOTYPE AS TABLE
	(
		NUMERO VARCHAR(20) PRIMARY KEY NONCLUSTERED NOT NULL,
		NOME_TITULAR VARCHAR(500),
		CPF_CNPJ_INPI_TITULAR VARCHAR(100),
		PAIS_TITULAR VARCHAR(50),
		UF_TITULAR CHAR(2),
		NOME_PROCURADOR VARCHAR(500),
		MARCA VARCHAR(1000),
		MARCA_ORTOGRAFADA VARCHAR(1000),
		MARCA_NAO_ORTOGRAFADA VARCHAR(1000),
		PRIORIDADE VARCHAR(100),
		DATA_PRIORIDADE DATE,
		NOME_PAIS_PRIORIDADE CHAR(2),
		TIPO_APRESENTACAO INT,
		TIPO_NATUREZA INT,
		CLASSE_INTERNACIONAL CHAR(5),
		CLASSE_1 CHAR(5),
		CLASSE_2 CHAR(5),
		CLASSE_3 CHAR(5),
		ESPECIFICACAO VARCHAR(MAX),
		APOSTILA VARCHAR(MAX),
		NUMERO_REFERENCIA VARCHAR(255),
		DATA_DEPOSITO DATE,
		DATA_CONCESSAO DATE,
		DATA_REGISTRO DATE,
		DATA_VIGENCIA DATE,
		MARCA_SEM_VOGAIS VARCHAR(1000)
	)
	WITH
    (MEMORY_OPTIMIZED = ON)
    
PRINT 'O Type "PROCESSOTYPE" foi criado com sucesso'
END
ELSE
  PRINT 'O Type "PROCESSOTYPE" já existe!'
GO

