SELECT
  CASE 
	WHEN (LEN(NUMERO_CLASSE) = 4) AND (LEFT(NUMERO_CLASSE, 1) != 'N')
	  THEN
		SUBSTRING(NUMERO_CLASSE, 1, 2)
	WHEN (LEN(NUMERO_CLASSE) = 5) AND (LEFT(NUMERO_CLASSE, 1) = 'N')
	  THEN
	    SUBSTRING(NUMERO_CLASSE, 4, 2)
  END AS CLASSE,

  CASE 
	WHEN (LEN(NUMERO_CLASSE) = 4) AND (LEFT(NUMERO_CLASSE, 1) != 'N')
	  THEN
		SUBSTRING(NUMERO_CLASSE, 3, 2)
  END AS SUB_CLASSE,

  CASE 
	WHEN (LEN(NUMERO_CLASSE) = 5) AND (LEFT(NUMERO_CLASSE, 1) = 'N')
	  THEN
		SUBSTRING(NUMERO_CLASSE, 2, 2)
  END AS EDICAO_CLASSE,
  *
FROM
  CLASSE


