IF NOT EXISTS (
				SELECT
				 *
				FROM 
				  SYSOBJECTS
				WHERE 
				  XTYPE = 'U'
				  AND NAME = 'PROCESSO_RADICAL' 
			 )
BEGIN
	CREATE TABLE PROCESSO_RADICAL
	(
	  ID              int identity
		constraint PK_PROCESSO_RADICAL
		primary key ,
	  NUMERO_PROCESSO varchar(20)    not null ,
	  RADICAL         nvarchar(2000) not null ,
	  LENGTH_RADICAL  int            not null ,
	  ID_TIPO_PROCESSO_RADICAL            INT NOT NULL,
	  MAIN                     bit,
	  BIGGER                   bit default 0
	)
	
	ALTER TABLE PROCESSO_RADICAL  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_RADICAL_TIPO] FOREIGN KEY(ID_TIPO_PROCESSO_RADICAL)
	REFERENCES TIPO_PROCESSO_RADICAL (ID)
	
	CREATE NONCLUSTERED INDEX [INDEX_PROCESSO_RADICAL] ON [dbo].[PROCESSO_DESPACHO] (ID_PROCESSO)
	CREATE NONCLUSTERED INDEX [INDEX_PROCESSO_RADICAL] ON [dbo].[PROCESSO_DESPACHO] (ID_DESPACHO)
	
	PRINT 'A Tabela "PROCESSO_RADICAL" foi criada com sucesso'
END
ELSE
  PRINT 'A Tabela "PROCESSO_RADICAL" já existe!'
GO