INSERT INTO dbo.ATRIBUTO
        ( CODIGO, DESCRICAO )
VALUES
( N'3791', N'Aditamento a petição' ), 
( N'3481', N'Anotação de alteração de nome, sede ou endereço' ), 
( N'3913', N'Anotação de limitação ou ônus' ), 
( N'P08', N'Anotação de transferência de titularidade' ), 
( N'3491', N'Anotação de transferência de titularidade decorrente de cessão' ), 
( N'3492', N'Anotação de transferência de titularidade decorrente de cisão' ), 
( N'3496', N'Anotação de transferência de titularidade decorrente de outros motivos' ), 
( N'3632', N'Apresentação de documentos de procuração' ), 
( N'3811', N'Apresentação de documentos: documentos de prioridade' ), 
( N'3818', N'Apresentação de documentos: outros documentos' ), 
( N'3371', N'Caducidade' ), 
( N'3725', N'Concessão de registro de marca e expedição de certificado no prazo ordinário' ), 
( N'8243', N'Cópia reprográfica simples' ), 
( N'3781', N'Correção de dados no processo devido a falha do interessado' ), 
( N'34015', N'Cumprimento de exigência' ), 
( N'34016', N'Cumprimento de exigência' ), 
( N'3821', N'Cumprimento de exigência decorrente do exame de conformidade em petição' ), 
( N'3381', N'Cumprimento de exigência decorrente do exame formal em pedido de registro' ), 
( N'3551', N'Desistência de pedido de registro de marca' ), 
( N'3831', N'Desistência de pedido de registro de marca' ), 
( N'3841', N'Desistência de petição' ), 
( N'3421', N'Devolução de prazo por falha do INPI' ), 
( N'3423', N'Devolução de prazo por falha do INPI' ), 
( N'3424', N'Devolução de prazo por falha do INPI' ), 
( N'3395', N'Manifestação' ), 
( N'3396', N'Manifestação [em petição]' ), 
( N'3392', N'Manifestação sobre caducidade' ), 
( N'3393', N'Manifestação sobre nulidade administrativa' ), 
( N'3391', N'Manifestação sobre oposição' ), 
( N'3851', N'Nomeação, destituição ou substituição de procurador' ), 
( N'3912', N'Notificação judicial' ), 
( N'3361', N'Nulidade administrativa de registro de marca' ), 
( N'3321', N'Oposição' ), 
( N'P03', N'Oposição' ), 
( N'36326', N'Outras petições' ), 
( N'P19', N'Outras petições' ), 
( N'3751', N'Prorrogação de registro de marca e expedição de certificado no prazo extraordinário' ), 
( N'3755', N'Prorrogação de registro de marca e expedição de certificado no prazo extraordinário' ), 
( N'3741', N'Prorrogação de registro de marca e expedição de certificado no prazo ordinário' ), 
( N'3745', N'Prorrogação de registro de marca e expedição de certificado no prazo ordinário' ), 
( N'P22', N'Prorrogação de registro de marca no prazo extraordinário' ), 
( N'P07', N'Prorrogação de registro de marca no prazo ordinário' ), 
( N'P04', N'Recurso' ), 
( N'33318', N'Recurso contra decisão em petição' ), 
( N'33317', N'Recurso contra decisão em processo de registro' ), 
( N'3331', N'Recurso contra indeferimento de pedido de registro de marca' ), 
( N'3871', N'Renúncia a mandato de procuração' ), 
( N'3552', N'Renúncia a registro de marca' ), 
( N'3881', N'Renúncia a registro de marca' ), 
( N'3661', N'Retificação por erro de publicação na RPI' ), 
( N'3663', N'Retificação por erro de publicação na RPI' ), 
( N'3241', NULL ), 
( N'3251', NULL ), 
( N'3261', NULL ), 
( N'3271', NULL ), 
( N'3281', NULL ), 
( N'3301', NULL ), 
( N'3401', NULL ), 
( N'3412', NULL ), 
( N'3414', NULL ), 
( N'3415', NULL ), 
( N'3416', NULL ), 
( N'3422', NULL ), 
( N'3482', NULL ), 
( N'3493', NULL ), 
( N'3494', NULL ), 
( N'3495', NULL ), 
( N'3634', NULL ), 
( N'3662', NULL ), 
( N'3664', NULL ), 
( N'3711', NULL ), 
( N'36328', NULL )

GO